#ifndef tim6_7_h
#define tim6_7_h

#include <stdint.h>

// 19.4.9 TIM6&TIM7 register map, p.629 " stm32f446xx-advanced.pdf "

#define TIM6_BASE 0x40001000UL
// #define TIM7_BASE 0x40001400UL

#define TIMx_CR1    0x00
#define TIM6_CR1 (*(volatile uint32_t *)(TIM6_BASE + TIMx_CR1))
/*
7 ARPE: Auto-reload preload enable
0: TIMx_ARR register is not buffered.
1: TIMx_ARR register is buffered.
- определяет, когда новое значение ARR начнет действовать, сразу или после UEV

3 OPM: One-pulse mode
0: Counter is not stopped at update event
1: Counter stops counting at the next update event (clearing the CEN bit).
- определяет, остановится ли таймер после одного периода счета, или будет работать непрерывно

2 URS: Update request source, this bit is set and cleared by software to select the UEV event sources.
0: Any of the following events generates an update interrupt or DMA request if enabled.
These events can be:
– Counter overflow/underflow
– Setting the UG bit
– Update generation through the slave mode controller
1: Only counter overflow/underflow generates an update interrupt or DMA request if enabled.
- определяет, какие события могут вызвать Update Interrupt или DMA Request

1 UDIS: Update disable, this bit is set and cleared by software to enable/disable UEV event generation.
0: UEV enabled. The Update (UEV) event is generated by one of the following events:
– Counter overflow/underflow
– Setting the UG bit
– Update generation through the slave mode controller
Buffered registers are then loaded with their preload values.
1: UEV disabled. The Update event is not generated, shadow registers keep their value
(ARR, PSC). However the counter and the prescaler are reinitialized if the UG bit is set or if
a hardware reset is received from the slave mode controller.
- определяет, будет ли генерироваться событие обновления (UEV, Update Event)

0 CEN: Counter enable
0: Counter disabled
1: Counter enabled
Note: Gated mode can work only if the CEN bit has been previously set by software. However
trigger mode can set the CEN bit automatically by hardware.
CEN is cleared automatically in one-pulse mode, when an update event occurs.
*/ 

#define TIMx_CR2    0x04 
#define TIM6_CR2 (*(volatile uint32_t *)(TIM6_BASE + TIMx_CR2))
/*

6:4 MMS[2:0]: Master mode selection
These bits are used to select the information to be sent in master mode to slave timers for
synchronization (TRGO). The combination is as follows:
- выбирает, что таймер "выдаёт наружу" через TRGO ( Trigger Output )

000: Reset - the UG bit from the TIMx_EGR register is used as a trigger output (TRGO). If
reset is generated by the trigger input (slave mode controller configured in reset mode) then
the signal on TRGO is delayed compared to the actual reset.
- TRGO в этом режиме привязан к биту UG (Update Generation) в TIMx_EGR

001: Enable - the Counter enable signal, CNT_EN, is used as a trigger output (TRGO). It is
useful to start several timers at the same time or to control a window in which a slave timer
is enabled. The Counter Enable signal is generated by a logic OR between CEN control bit
and the trigger input when configured in gated mode.
When the Counter Enable signal is controlled by the trigger input, there is a delay on TRGO,
except if the master/slave mode is selected (see the MSM bit description in the TIMx_SMCR
register).
- TRGO показывает, работает ли таймер

010: Update - The update event is selected as a trigger output (TRGO). For instance a
master timer can then be used as a prescaler for a slave timer.
- "каждый переполнившийся таймерный цикл становится аппаратным триггером"

! - более продвинутые режимы, не трогаем пока
*/

#define TIMx_DIER   0x0C   
#define TIM6_DIER  (*(volatile uint32_t *)(TIM6_BASE + TIMx_DIER))
/*
8 UDE: Update DMA request enable
0: Update DMA request disabled.
1: Update DMA request enabled.
- DMA (Direct Memory Access) — это механизм, который позволяет периферии читать/писать в память без участия CPU.

Bit 0 UIE: Update interrupt enable
0: Update interrupt disabled.
1: Update interrupt enabled.
- IRQ (Interrupt Request) — "процессор прерывают и заставляют выполнить код по событию"
*/

#define TIMx_SR     0x10
#define TIM6_SR    (*(volatile uint32_t *)(TIM6_BASE + TIMx_SR))
/*
0 UIF: Update interrupt flag
This bit is set by hardware on an update event. It is cleared by software.
0: No update occurred.
1: Update interrupt pending. This bit is set by hardware when the registers are updated:
– At overflow or underflow and if UDIS = 0 in the TIMx_CR1 register.
– When CNT is reinitialized by software using the UG bit in the TIMx_EGR register, if URS = 0
and UDIS = 0 in the TIMx_CR1 register

UIF = "таймер уже досчитал и обновился"
UIE = "разрешить реакцию CPU на это"
IRQ = "CPU реально вызвали" ( код обработчика прерывания )
*/

#define TIMx_EGR    0x14
#define TIM6_EGR   (*(volatile uint32_t *)(TIM6_BASE + TIMx_EGR))
/*
0 UG: Update generation
This bit can be set by software, it is automatically cleared by hardware.
0: No action.
1: Re-initializes the timer counter and generates an update of the registers. Note that the
prescaler counter is cleared too (but the prescaler ratio is not affected).
- UG = "немедленно сделать Update Event и перезапустить таймер" : set PSC/ARR → UG → start
*/

#define TIMx_CNT    0x24   
#define TIM6_CNT   (*(volatile uint32_t *)(TIM6_BASE + TIMx_CNT))
/*
15:0 CNT[15:0]: Counter value ( 0 - 65535 ) - но фактический предел задаётся ARR
*/ 

#define TIMx_PSC    0x28
#define TIM6_PSC   (*(volatile uint32_t *)(TIM6_BASE + TIMx_PSC))
/*
15:0 PSC[15:0]: Prescaler value
fCK_PSC / (PSC[15:0] + 1) - формула, PSC = ( 0 - 65535 ), но деление = PSC + 1
*/

#define TIMx_ARR    0x2C
#define TIM6_ARR   (*(volatile uint32_t *)(TIM6_BASE + TIMx_ARR))
/*
15:0 ARR[15:0]: Auto-reload value
- ARR = "верхняя граница счёта таймера",  работает только если ARR ≠ 0, ( 0 - 65535 )
*/

#endif // tim6_7_h
